spring.application.name=event_management_system

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/event_management_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8080

# JWT Secret
# JWT
app.jwt.secret=VGhpc0lzQVNlY3VyZUpXVFNlY3JldEtleUZvckV2ZW50TWFuYWdlbWVudFN5c3RlbTEyMzQ1Njc4OTA=
app.jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG