# Safe local development defaults
DB_USERNAME=root
DB_PASSWORD=root
JWT_SECRET=EFihITg9SNyP5tBGTkyUMhgq3yvq8UcZFEP38N+4iok=

spring.datasource.username=root
spring.datasource.password=root
app.jwt.secret=EFihITg9SNyP5tBGTkyUMhgq3yvq8UcZFEP38N+4iok=

# Dev-only logging & sql overrides
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG

# Razorpay Local Dev Configuration
RAZORPAY_KEY_ID=rzp_test_TDnNEoRLz2m96G
RAZORPAY_KEY_SECRET=25E7Iiv68Owji2k1dKm18quw
RAZORPAY_WEBHOOK_SECRET=devsecret

